# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trustkitfirebasesample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core', '~> 4.9.0'
  pod 'Firebase/Database', '~> 4.9.0'
  pod 'Firebase/Storage', '~> 4.9.0'
  pod 'Firebase/Auth', '~> 4.9.0'
  pod 'TrustKit', '~> 1.5'
  # Pods for trustkitfirebasesample

end
